### PR TITLE
Add disabling option for input

### PR DESCRIPTION
**Pull request by rrodionov91**
I need possibility to disable input

### CODE REVIEW

**Review by skegel13 — COMMENTED** [review]
The plugin should already support the :disabled attribute using v-bind="@attrs". Does this not work for you?

**Comment by rrodionov91** [comment]
I'm not sure what this syntax mean (v-bind="@attrs"). Can you give me an example?
I try :disabled="disabled" and v-bind="{ disabled: true }" but it still not work.

**Comment by skegel13** [comment]
If you add the attribute 'disabled="true"' or ':disabled="true"', it should disable the input. You are using the latest version correct and Vue 2.4 or higher?

**Comment by rrodionov91** [comment]
Yes, i updated vue and it works! Thank you very much :)

**Pull request closed without merging**
