### PR TITLE
Fix CSS being removed by tree shaking in Webpack

### LINKED ISSUE #30: 为什么样式在部署环境没有引入的问题
VuePassword

### PR DESCRIPTION
**Pull request by JJCLane**
When running a build for production, the CSS from the vue-password component was removed. This fixes #30.

### CODE REVIEW

**Comment by skegel13** [comment]
@JJCLane I will take a look at this, hopefully later today. I see you keep adding commits, let me know when you have it how you think it should be.

**Comment by JJCLane** [comment]
@skegel13 Should be in a good shape now 👍 Sorry I realise it was just pulling everything from my master branch, but I also fixed a bug where the password field was automatically being focused on page load which fixes #25.

**Comment by skegel13** [comment]
@JJCLane Can you break this up into multiple PRs, one for the css changes and one for the focus changes?

**Comment by JJCLane** [comment]
Done! I'll close this in favour of #32 and #33. Thanks @skegel13

**Pull request closed without merging**
